### ISSUE TITLE
Mission ID1454 and mission ID1481 are still unable to use mission delivery

### ISSUE THREAD

**Issue by 7521468** [Suprcode/mir-eternal#166]
@periko92 @bernatvadell 在两个任务中使用物品传送仍然不起作用，谢谢，请查看任务ID1454和任务ID1481      #142

**Comment by periko92** [comment]
Dear,
Did you update database? Because if you check files, it's already fixed.
  "CanTeleport": true,
  "TeleportCostId": 2326,
  "TeleportCostValue": 1,

in 1454 and 1481
https://github.com/Suprcode/mir-eternal/blob/main/Database/System/Quests/1481-The%20Vengeance%20(I).txt
https://github.com/Suprcode/mir-eternal/blob/main/Database/System/Quests/1454-The%20Arousal%20(XI).txt
