### ISSUE TITLE
Shops not loading

### ISSUE THREAD

**Issue by KingdomMir2** [Suprcode/mir-eternal#50]
Using everthing from this git , but npcs dont sell anything?

**Comment by bernatvadell** [comment]
Are u using the last client version?

**Comment by KingdomMir2** [comment]
Pretty sure i updated the client right

**Comment by KingdomMir2** [comment]
![image](https://user-images.githubusercontent.com/54754739/183672719-94c2e30d-50be-4585-a936-36255c78cfc1.png)

**Comment by KingdomMir2** [comment]
How you update from here?
![image](https://user-images.githubusercontent.com/54754739/183676526-1694bafa-2fd6-4bf5-afc2-11089c5c3faf.png)

**Comment by bernatvadell** [comment]
Open official launcher, and click on play button:

![image](https://user-images.githubusercontent.com/17298604/183677002-83fcd53f-d3a1-4844-b6ec-f4f3bd5d1e3c.png)

**Comment by Johnyl1** [comment]
How about sharing how to put stuff in english, that might help a lill more no?

**Comment by bernatvadell** [comment]
We are still working on the tool to translate things, at the moment the process is very manual. The translations that you see now, are partially placed from the official conquera in English.

We wanted to test if we can modify the client, we already have that ability, but the focus is still on stabilizing the server.

**Comment by Johnyl1** [comment]
so , we have to hunt for bugs with everything in chinese when we can have stuff in English!! Makes sence!!

**Comment by bernatvadell** [comment]
Half of the things are broken when pasting the English files. Everything will come.

**Comment by periko92** [comment]
> so , we have to hunt for bugs with everything in chinese when we can have stuff in English!! Makes sence!!

Dear. I think your interest is only to have a server fully translated in English. Instead of opening server to play, you can have a look on the code and try to improve. At the moment we are just 4 peeps working on server files and client files. There's no English tool for client. Just English files from old client. You can out these in your new client and you will be able to see most of the things in English. 
Before get full translated , need to fix most of bugs, implement the new codes in game,  as there's a lot of things uncompleted. I know you all like to play and have a brand new server files. But remember these files were obfuscated and we have only part of the code. Hope you don't understand bad my words. But I'm getting tired of seeing people opening posts and bugs "this is not worming" please. Before post make sure you got the latest  update from source code and client updated ;)

**Comment by KingdomMir2** [comment]
I am thankfull for all the work , i am just trying to make i got all the files needed to try and play and find bugs.
