### ISSUE TITLE
Hunting WT crashed server!

### ISSUE THREAD

**Issue by Johnyl1** [Suprcode/mir-eternal#51]
![image](https://user-images.githubusercontent.com/63940002/183708369-da5ef111-bff2-4519-8b0b-6f8e3ea3cc61.png)
 Was hunting on 2nd floor and server crashed!

**Comment by periko92** [comment]
well, thanks for your support, i've been testing all maps around WT, and ZT, and i've see a difference on maplist,

![image](https://user-images.githubusercontent.com/109764547/183726973-86d34a2d-b1ef-4f0c-94e1-b8526760de10.png)

as you can see there's few names "bad translated" or atleast with the same name "WoomaTemple1st".
i've been playing around these maps, going on doors (you can use @Move CharName MapId MapX MapY)
and my server on debugging mode at VS, didn't crash, also i've been killing mobs around these maps and still no crash,

thanks for your info, but if you could supply more info about that, or atleast if you trying to open the server on "live server" style, you can run it in debug mode, so if it crash, we can invest more time looking at the bug, instead of an screenshot with not more info than "GS has crashed".

Thanks for your time testing the files,
Erik

**Comment by Johnyl1** [comment]
i can try to setup visual studio on the main server...

**Comment by Johnyl1** [comment]
![image](https://user-images.githubusercontent.com/63940002/183755685-a88c89f1-5190-459e-8a09-1b4055f08d3d.png)
 Just crashed again this time i was running away on the KR WT

![image](https://user-images.githubusercontent.com/63940002/183755781-b575c8cb-b4f4-4336-8e32-f55e19807276.png)
